version: '3.7'

services:
  proxy:
    image: rt_proxy:${TAG:-latest}
    build:
      context: ./proxy
    volumes:
      - backend_static_django:/usr/src/project/static_django
    depends_on:
      - backend
      - frontend
    networks:
    - net
  frontend:
    image: rt_frontend:${TAG:-latest}
    build:
      context: ./frontend
      args:
        FRONTEND_PRODUCTION_URL: ${FRONTEND_API_URL}
    networks:
    - net
  backend:
    image: rt_backend:${TAG:-latest}
    build:
      context: ./backend
    volumes:
      - backend_static_django:/usr/src/project/static_django/
    environment:
      BACKEND_DEBUG_MODE: ${BACKEND_DEBUG_MODE}
      BACKEND_SECRET_KEY: ${BACKEND_SECRET_KEY}
      BACKEND_ALLOWED_HOSTS: ${BACKEND_ALLOWED_HOSTS}

      DJANGO_SUPERUSER_USERNAME: ${BACKEND_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${BACKEND_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${BACKEND_SUPERUSER_PASSWORD}

      BACKEND_ML_ADDRESS: ${BACKEND_ML_ADDRESS}
      BACKEND_YANDEX_MAPS_API_KEY: ${BACKEND_YANDEX_MAPS_API_KEY}

      BACKEND_DEFAULT_DB: ${BACKEND_DEFAULT_DB}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
    - net

volumes:
  backend_static_django:
  postgres_data:

networks:
  net:
    driver: overlay
