version: '3.7'

services:
  proxy:
    image: rt_proxy
    build:
      context: ./proxy
    ports:
      - ${PROXY_PORT}:8080
    volumes:
      - ./backend:/usr/src/project
      - backend_static_django:/usr/src/project/static_django
    depends_on:
      - backend
      - frontend
  frontend:
    image: rt_frontend
    build:
      context: ./frontend
  backend:
    image: rt_backend
    build:
      context: ./backend
    volumes:
      - ./backend/media/:/usr/src/project/media/
      - backend_static_django:/usr/src/project/static_django/
    environment:
      BACKEND_DEBUG_MODE: ${BACKEND_DEBUG_MODE}
      BACKEND_SECRET_KEY: ${BACKEND_SECRET_KEY}
      BACKEND_ALLOWED_HOSTS: ${BACKEND_ALLOWED_HOSTS}

      DJANGO_SUPERUSER_USERNAME: ${BACKEND_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${BACKEND_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${BACKEND_SUPERUSER_PASSWORD}

      BACKEND_IMAGE_MAX_SIZE: ${BACKEND_IMAGE_MAX_SIZE}
      BACKEND_AUDIO_MAX_SIZE: ${BACKEND_AUDIO_MAX_SIZE}

      BACKEND_DEFAULT_DB: ${BACKEND_DEFAULT_DB}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      BACKEND_DEFAULT_STORAGE: ${BACKEND_DEFAULT_STORAGE}
      AWS_S3_ENDPOINT_URL: ${BACKEND_AWS_S3_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${BACKEND_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${BACKEND_AWS_SECRET_ACCESS_KEY}
      AWS_STORAGE_BUCKET_NAME: ${BACKEND_AWS_STORAGE_BUCKET_NAME}
      BACKEND_AWS_S3_REGION_NAME: ${BACKEND_AWS_S3_REGION_NAME}
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
volumes:
  backend_static_django:
  postgres_data:
